### ISSUE TITLE
Is it possible to use NSNotificationCenter from Hyperloop?

### ISSUE THREAD

**Issue by qasim90** [shouse/awesome-hyperloop-titanium#6]
After a lot of research I couldn't find a single example to use `NSNotificationCenter` from hyperloop. @shouse I would be very thankful if you can give some example. [Check details here.](https://stackoverflow.com/questions/52257709/titanium-use-nsnotificationcenter-using-hyperloop)

**Comment by shouse** [comment]
@qasim90 After clicking through to the SO question, it appears you have an answer, so I'll close this issue.  I'd gladly accept a PR with your solution!
